=== PlatformOfTrust/standards/v1/Schema/Identity/Equipment/Device/Luminaire.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "properties": {
        "@context": {
            "type": "string",
            "minLength": 1
        },
        "@type": {
            "type": "string",
            "minLength": 1,
            "enum": [
                "Luminaire"
            ]
        },
        "data": {
            "title": "",
            "description": "",
            "type": "object",
            "properties": {
                "serialNumber": {
                    "title": "Serial number",
                    "description": "Unique identifier for the device instance",
                    "type": "string"
                },
                "lampType": {
                    "title": "Lamp type",
                    "description": "Lamp type",
                    "type": "string"
                },
                "idLocal": {
                    "title": "Local identifier",
                    "description": "",
                    "type": "string"
                },
                "colorCode": {
                    "title": "Color code",
                    "description": "",
                    "type": "string"
                },
                "width": {
                    "title": "Width",
                    "description": "",
                    "type": "string"
                },
                "ifcGuid": {
                    "title": "IFC GUID",
                    "description": "IFC standard based Globally Unique Identifier",
                    "type": "string"
                },
                "industryDomain": {
                    "title": "Industry sector name",
                    "description": "Industry sector name to which the device belongs",
                    "type": "string"
                },
                "lightVisor": {
                    "title": "Visor",
                    "description": "Type of visor",
                    "type": "string"
                },
                "areaGross": {
                    "title": "Area - gross",
                    "description": "",
                    "type": "string"
                },
                "volume": {
                    "title": "Volume",
                    "description": "",
                    "type": "string"
                },
                "typeName": {
                    "title": "Material",
                    "description": "Main material which device is composed",
                    "type": "string"
                },
                "lightFlux": {
                    "title": "Flux",
                    "description": "Rated luminous flux acc. IEC 62722-2-1",
                    "type": "string"
                },
                "lightDirection": {
                    "title": "Lighting type",
                    "description": "Direction of light (direct or indirect)",
                    "type": "string"
                },
                "electricityCurrent": {
                    "title": "Electric current",
                    "description": "An electric current is the rate of flow of electric charge past a point",
                    "type": "string"
                },
                "function": {
                    "title": "",
                    "description": "",
                    "type": "string"
                },
                "name": {
                    "title": "Apartment name",
                    "description": "",
                    "type": "string"
                },
                "lightColor": {
                    "title": "Colour temperature",
                    "description": "Light color temperature",
                    "type": "string"
                },
                "controlMechanism": {
                    "title": "Type of control gear",
                    "description": "Type of control mechanism or gear",
                    "type": "string"
                },
                "connectionMechanism": {
                    "title": "Connection method/wiring",
                    "description": "Connection mechanism for wiring",
                    "type": "string"
                },
                "height": {
                    "title": "Height",
                    "description": "",
                    "type": "string"
                },
                "thickness": {
                    "title": "Thickness",
                    "description": "",
                    "type": "string"
                },
                "processCapability": {
                    "title": "Process capability",
                    "description": "Process which device is capable executing to produce output",
                    "type": "string"
                },
                "colorName": {
                    "title": "Color",
                    "description": "",
                    "type": "string"
                },
                "power": {
                    "title": "Power (W)",
                    "description": "Power measured in Watts",
                    "type": "string"
                },
                "protectionDegree": {
                    "title": "Degree of protection",
                    "description": "Class or degree of protection (IP)",
                    "type": "string"
                },
                "status": {
                    "title": "Project status",
                    "description": "",
                    "type": "string"
                },
                "controlMode": {
                    "title": "Control mode",
                    "description": "Type of control mode",
                    "type": "string"
                },
                "weight": {
                    "title": "Weight",
                    "description": "",
                    "type": "string"
                },
                "areaNet": {
                    "title": "Area - net",
                    "description": "",
                    "type": "string"
                },
                "length": {
                    "title": "Length",
                    "description": "",
                    "type": "string"
                },
                "installationTypeAvailable": {
                    "title": "Installation/mounting type available",
                    "description": "Installation type available",
                    "type": "string"
                },
                "installationType": {
                    "title": "Installation/mounting type",
                    "description": "Actual installation type for the device",
                    "type": "string"
                },
                "lightColorRenderingIndex": {
                    "title": "Colour rendering index",
                    "description": "Light color rendering index (CRI)",
                    "type": "string"
                },
                "descriptionGeneral": {
                    "title": "Description",
                    "description": "Description",
                    "type": "string"
                },
                "categorizationLocal": {
                    "title": "Space type - local",
                    "description": "Categorisation name given locally",
                    "type": "string"
                },
                "electricityPower": {
                    "title": "Power",
                    "description": "Maximum system power",
                    "type": "string"
                },
                "ifcElementName": {
                    "title": "IFC element name",
                    "description": "IFC standard element name",
                    "type": "string"
                },
                "protectionResilience": {
                    "title": "Impact strength",
                    "description": "Class or degree of impact strength",
                    "type": "string"
                },
                "ifcElementType": {
                    "title": "IFC element type",
                    "description": "IFC standard element type",
                    "type": "string"
                }
            }
        },
        "metadata": {
            "title": "Metadata",
            "description": "Metadata container",
            "type": "object",
            "properties": {
                "updatedAt": {
                    "title": "Update time",
                    "description": "Time when the data is updated",
                    "type": "string"
                },
                "updatedBy": {
                    "title": "Updater",
                    "description": "Updater of an identity",
                    "type": "string"
                },
                "createdBy": {
                    "title": "Creator",
                    "description": "Creator of and identity",
                    "type": "string"
                },
                "createdAt": {
                    "title": "Creation time",
                    "description": "Time when the data is created",
                    "type": "string"
                }
            }
        },
        "function": {
            "title": "",
            "description": "",
            "type": "string"
        },
        "id": {
            "title": "",
            "description": "",
            "type": "string"
        }
    },
    "required": [
        "id",
        "data",
        "@context",
        "@type"
    ]
}

=== PlatformOfTrust/standards/v2/DataExample/Identity/Equipment/Device/Luminaire.json
{
    "@context": "https://standards-ontotest.oftrust.net/v2/Schema/Identity/Equipment/Device/Luminaire/",
    "@type": "Luminaire",
    "id": "",
    "data": {
        "electricityPower": "",
        "serialNumber": "",
        "industryDomain": "",
        "lightColorRenderingIndex": "",
        "volume": "",
        "lightDirection": "",
        "length": "",
        "controlMode": "",
        "lampType": "",
        "name": "",
        "height": "",
        "lightVisor": "",
        "idLocal": "",
        "typeName": "",
        "descriptionGeneral": "",
        "connectionMechanism": "",
        "installationType": "",
        "ifcElementType": "",
        "width": "",
        "controlMechanism": "",
        "protectionResilience": "",
        "colorCode": "",
        "weight": "",
        "colorName": "",
        "status": "",
        "thickness": "",
        "categorizationETIM": "",
        "installationTypeAvailable": "",
        "power": "",
        "areaGross": "",
        "ifcElementName": "",
        "categorizationLocal": "",
        "lightFlux": "",
        "ifcGuid": "",
        "areaNet": "",
        "electricityCurrent": "",
        "protectionDegree": "",
        "lightColor": ""
    },
    "metadata": {
        "updatedBy": "",
        "updatedAt": "",
        "createdAt": "",
        "createdBy": ""
    },
    "function": ""
}
