=== PlatformOfTrust/standards/v2/Schema/Identity/Equipment/Device/Cabel.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "properties": {
        "@context": {
            "type": "string",
            "minLength": 1,
            "const": "https://standards-ontotest.oftrust.net/v2/Context/Identity/Equipment/Device/Cabel/"
        },
        "@type": {
            "type": "string",
            "minLength": 1,
            "enum": [
                "Cabel"
            ],
            "const": "Cabel"
        },
        "function": {
            "title": "",
            "description": "",
            "type": "string"
        },
        "metadata": {
            "title": "Metadata",
            "description": "Metadata container",
            "type": "object",
            "properties": {
                "updatedAt": {
                    "title": "Update time",
                    "description": "Time when the data is updated",
                    "type": "string"
                },
                "createdAt": {
                    "title": "Creation time",
                    "description": "Time when the data is created",
                    "type": "string"
                },
                "updatedBy": {
                    "title": "Updater",
                    "description": "Updater of an identity",
                    "type": "string"
                },
                "createdBy": {
                    "title": "Creator",
                    "description": "Creator of and identity",
                    "type": "string"
                }
            }
        },
        "data": {
            "title": "",
            "description": "",
            "type": "object",
            "properties": {
                "areaGross": {
                    "title": "Gross area",
                    "description": "Gross area size",
                    "type": "string"
                },
                "acidityLevel": {
                    "title": "Acidity",
                    "description": "Euro class acidity according to EN 13501-6",
                    "type": "string"
                },
                "url": {
                    "title": "URL address",
                    "description": "URL address",
                    "type": "string"
                },
                "categorizationETIM": {
                    "title": "ETIM class name",
                    "description": "Product category name based on ETIM standard ((European Technical Information Model).",
                    "type": "string"
                },
                "fireReaction": {
                    "title": "Reaction-to-fire",
                    "description": "Reaction-to-fire class according to EN 13501-6",
                    "type": "string"
                },
                "fireResistanceInsulation": {
                    "title": "Insulation integrity",
                    "description": "Insulation integrity",
                    "type": "string"
                },
                "amountCores": {
                    "title": "Number of cores",
                    "description": "Number of cores",
                    "type": "string"
                },
                "ifcElementType": {
                    "title": "IFC element type",
                    "description": "Element type based on IFC standard",
                    "type": "string"
                },
                "colorCode": {
                    "title": "Color code",
                    "description": "Color code",
                    "type": "string"
                },
                "categorizationLocal": {
                    "title": "Local category",
                    "description": "Categorisation name given locally",
                    "type": "string"
                },
                "fireClassification": {
                    "title": "Circuit integrity",
                    "description": "Circuit integrity",
                    "type": "string"
                },
                "electricityVoltageNominal": {
                    "title": "Nominal Voltage U",
                    "description": "Nominal voltage (U)",
                    "type": "string"
                },
                "thickness": {
                    "title": "Thickness",
                    "description": "Thickness",
                    "type": "string"
                },
                "ifcGuid": {
                    "title": "IFC GUID",
                    "description": "IFC standard based Globally Unique Identifier",
                    "type": "string"
                },
                "ifcElementName": {
                    "title": "IFC element name",
                    "description": "Element name based on IFC standard",
                    "type": "string"
                },
                "length": {
                    "title": "Length",
                    "description": "Lenght",
                    "type": "string"
                },
                "fireSmokeDevelopment": {
                    "title": "Smoke development",
                    "description": "Smoke development class according to EN 13501-6",
                    "type": "string"
                },
                "electricityCurrent": {
                    "title": "Electric current",
                    "description": "An electric current is the rate of flow of electric charge past a point",
                    "type": "string"
                },
                "width": {
                    "title": "Width",
                    "description": "Object width",
                    "type": "string"
                },
                "power": {
                    "title": "Power (W)",
                    "description": "Power measured in Watts",
                    "type": "string"
                },
                "amountFibres": {
                    "title": "Number of fibres",
                    "description": "Number of fibres",
                    "type": "string"
                },
                "areaNet": {
                    "title": "Net area",
                    "description": "Net area size",
                    "type": "string"
                },
                "installationType": {
                    "title": "Installation/mounting type",
                    "description": "Installation type description or type/classification",
                    "type": "string"
                },
                "status": {
                    "title": "Life-cycle status",
                    "description": "Life-cycle status",
                    "type": "string"
                },
                "typeNameConductor": {
                    "title": "Conductor material",
                    "description": "Conductor material",
                    "type": "string"
                },
                "weight": {
                    "title": "Weight",
                    "description": "Object weight",
                    "type": "string"
                },
                "protectionCommon": {
                    "title": "Screen over stranding",
                    "description": "Screen over stranding",
                    "type": "string"
                },
                "descriptionGeneral": {
                    "title": "Description",
                    "description": "Description",
                    "type": "string"
                },
                "fireFlamingParticlesDevelopment": {
                    "title": "Flaming droplets/particles",
                    "description": "Euro class flaming droplets/particles according to EN 13501-6",
                    "type": "string"
                },
                "protectionTypeStrandingElement": {
                    "title": "Screen over stranding element",
                    "description": "Screen type over stranding element",
                    "type": "string"
                },
                "diameterOuter": {
                    "title": "Outer diamater",
                    "description": "Outer diameter (approximately)",
                    "type": "string"
                },
                "industryDomain": {
                    "title": "Industry sector name",
                    "description": "Industry sector name to which the device belongs",
                    "type": "string"
                },
                "serialNumber": {
                    "title": "Serial number",
                    "description": "Serial number",
                    "type": "string"
                },
                "volume": {
                    "title": "Volume",
                    "description": "Volume of the object",
                    "type": "string"
                },
                "installationTypeAvailable": {
                    "title": "Installation/mounting type available",
                    "description": "Installation or mounting types available (can be multiple types)",
                    "type": "string"
                },
                "height": {
                    "title": "Height",
                    "description": "Height",
                    "type": "string"
                },
                "name": {
                    "title": "Name",
                    "description": "Name",
                    "type": "string"
                },
                "idLocal": {
                    "title": "Local identifier",
                    "description": "Locally given identifier",
                    "type": "string"
                },
                "typeName": {
                    "title": "Material",
                    "description": "Material name or type (main material)",
                    "type": "string"
                },
                "colorName": {
                    "title": "Color",
                    "description": "Color name",
                    "type": "string"
                }
            }
        },
        "@id": {
            "title": "",
            "description": "",
            "type": "string"
        }
    },
    "required": [
        "data",
        "@context",
        "@type",
        "@id"
    ]
}

=== PlatformOfTrust/standards/v2/DataExample/Identity/Equipment/Device/Cabel.json
{
    "@context": "https://standards-ontotest.oftrust.net/v2/Context/Identity/Equipment/Device/Cabel/",
    "@type": "Cabel",
    "@id": "",
    "data": {
        "fireClassification": "",
        "height": "",
        "fireSmokeDevelopment": "",
        "power": "",
        "electricityVoltageNominal": "",
        "installationType": "",
        "colorCode": "",
        "areaNet": "",
        "url": "",
        "fireFlamingParticlesDevelopment": "",
        "acidityLevel": "",
        "status": "",
        "categorizationLocal": "",
        "idLocal": "",
        "amountCores": "",
        "fireReaction": "",
        "ifcElementName": "",
        "weight": "",
        "amountFibres": "",
        "industryDomain": "",
        "installationTypeAvailable": "",
        "volume": "",
        "typeNameConductor": "",
        "width": "",
        "serialNumber": "",
        "protectionCommon": "",
        "categorizationETIM": "",
        "length": "",
        "typeName": "",
        "diameterOuter": "",
        "name": "",
        "ifcElementType": "",
        "descriptionGeneral": "",
        "colorName": "",
        "protectionTypeStrandingElement": "",
        "areaGross": "",
        "ifcGuid": "",
        "electricityCurrent": "",
        "thickness": "",
        "fireResistanceInsulation": ""
    },
    "metadata": {
        "updatedAt": "",
        "createdBy": "",
        "updatedBy": "",
        "createdAt": ""
    },
    "function": ""
}
