=== PlatformOfTrust/standards/v2/Source/DataProduct/Document/v3.0/ParametersSchema.json
{
   "$schema":"http://json-schema.org/draft-06/schema#",
   "$id":"https://standards-ontotest.oftrust.net/v2/Schema/DataProductParameters/Document",
   "type":"object",
   "required":[
      
   ],
   "properties":{
      "@context":{
         "$id":"#/properties/@context",
         "type":"string",
         "const":"https://standards-ontotest.oftrust.net/v2/Context/DataProductParameters/Document/",
         "title":"JSON-LD context url",
         "description":"JSON-LD context url with terms required to understand data product content."
      },
      "productCode":{
         "$id":"#/properties/productCode",
         "type":"string",
         "title":"Productcode",
         "description":"Name of the product."
      },
      "timestamp":{
         "$id":"#/properties/timestamp",
         "type":"string",
         "title":"Timestamp of the request",
         "description":"Timestamp of the request."
      },
      "parameters":{
         "$id":"#/properties/parameters",
         "type":"object",
         "title":"Actual data product parameters",
         "description":"An explanation about the purpose of this instance.",
         "required":[
            
         ],
         "properties":{
            "targetObject":{
               "$id":"#/properties/parameters/properties/targetObject",
               "type":"string",
               "title":"Target object",
               "description":"Target object."
            },
            "period":{
               "$id":"#/properties/parameters/properties/period",
               "type":"string",
               "title":"Period",
               "description":"Period"
            },
            "limit":{
               "$id":"#/properties/parameters/properties/limit",
               "type":"integer",
               "title":"Limit",
               "description":"Limit."
            },
            "offset":{
               "$id":"#/properties/parameters/properties/offset",
               "type":"integer",
               "title":"Offset",
               "description":"Number of signing processes to offset. Default is 0."
            }
         }
      }
   }
}

=== PlatformOfTrust/standards/v2/Source/DataProduct/Document/v3.0/ParametersExample.json
{
   "@context":"https://standards-ontotest.oftrust.net/v2/Context/DataProductParameters/Document/",
   "productCode":"multidata-product-1",
   "timestamp":"2019-10-19T13:20:09+00:00",
   "parameters":{
      "targetObject":"object id",
      "period":"2015-12-31T23:00Z/2016-12-31T23:00Z",
      "limit":20,
      "offset":0
   }
}
