=== PlatformOfTrust/standards/v2/Source/DataProduct/Report/OrganizationTrustCategory/v3.2/ParametersSchema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$id": "https://standards-ontotest.oftrust.net/v2/Schema/DataProductParameters/Report/OrganizationTrustCategory",
    "type": "object",
    "required": [],
    "properties": {
        "@context": {
            "$id": "#/properties/@context",
            "type": "string",
            "const": "https://standards-ontotest.oftrust.net/v2/Context/DataProductParameters/Report/OrganizationTrustCategory/",
            "title": "JSON-LD context url",
            "description": "JSON-LD context url with terms required to understand data product content."
        },
        "productCode": {
            "$id": "#/properties/productCode",
            "type": "string",
            "title": "Product code",
            "description": "Product code."
        },
        "timestamp": {
            "$id": "#/properties/timestamp",
            "type": "string",
            "title": "Time stamp",
            "description": "Time stamp."
        },
        "parameters": {
            "$id": "#/properties/parameters",
            "type": "object",
            "title": "Data product parameters",
            "description": "Data product parameters.",
            "required": [],
            "properties": {
                "registrationCountry": {
                    "$id": "#/properties/parameters/properties/registrationCountry",
                    "type": "string",
                    "title": "Registration Country",
                    "description": "Country in which the organization is registered."
                },
                "idOfficial": {
                    "$id": "#/properties/parameters/properties/idOfficial",
                    "type": "string",
                    "title": "Official identifier",
                    "description": "Government (official authority) assigned identifier."
                }
            }
        }
    }
}

=== PlatformOfTrust/standards/v2/Source/DataProduct/Report/OrganizationTrustCategory/v2.0/ParametersExample.json
{
   "@context":"https://standards-ontotest.oftrust.net/v2/Context/DataProductParameters/Report/OrganizationTrustCategory/",
   "productCode":"multidata-product-1",
   "timestamp":"2019-10-19T13:20:09+00:00",
   "parameters":{
      "period":"2015-12-31T23:00Z/2016-12-31T23:00Z",
      "targetObject":{
         "@type":"Report"
      }
   }
}

=== PlatformOfTrust/standards/v2/Source/DataProduct/Report/OrganizationTrustCategory/v3.0/ParametersExample.json
{
   "@context":"https://standards-ontotest.oftrust.net/v2/Context/DataProductParameters/Report/OrganizationTrustCategory/",
   "productCode":"multidata-product-1",
   "timestamp":"2019-10-19T13:20:09+00:00",
   "parameters":{
      "registrationCountry":"Finland",
      "idOfficial":"1234567-1"
   }
}
