=== PlatformOfTrust/standards/v2/Schema/Identity/Event.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "properties": {
        "@context": {
            "type": "string",
            "minLength": 1,
            "const": "https://standards-ontotest.oftrust.net/v2/Context/Identity/Event/"
        },
        "@type": {
            "type": "string",
            "minLength": 1,
            "enum": [
                "Event"
            ],
            "const": "Event"
        },
        "locationName": {
            "title": "Location name",
            "description": "Location name",
            "type": "string"
        },
        "metadata": {
            "title": "Metadata",
            "description": "Metadata container",
            "type": "object",
            "properties": {
                "createdBy": {
                    "title": "Creator",
                    "description": "Creator of and identity",
                    "type": "string"
                },
                "updatedAt": {
                    "title": "Update time",
                    "description": "Time when the data is updated",
                    "type": "string"
                },
                "updatedBy": {
                    "title": "Updater",
                    "description": "Updater of an identity",
                    "type": "string"
                },
                "createdAt": {
                    "title": "Creation time",
                    "description": "Time when the data is created",
                    "type": "string"
                }
            }
        },
        "data": {
            "title": "",
            "description": "",
            "type": "object",
            "properties": {
                "name": {
                    "title": "Name",
                    "description": "Name.",
                    "type": "string"
                },
                "startDateTime": {
                    "title": "Start time",
                    "description": "Start time",
                    "type": "string"
                },
                "endDateTime": {
                    "title": "End time",
                    "description": "End time",
                    "type": "string"
                },
                "url": {
                    "title": "URL address",
                    "description": "URL address.",
                    "type": "string"
                },
                "duration": {
                    "title": "Duration",
                    "description": "Duration (time)",
                    "type": "string"
                },
                "categorizationLocal": {
                    "title": "Local category",
                    "description": "Categorisation name given locally.",
                    "type": "string"
                },
                "descriptionGeneral": {
                    "title": "Description",
                    "description": "Description",
                    "type": "string"
                }
            }
        },
        "@id": {
            "title": "",
            "description": "",
            "type": "string"
        }
    },
    "required": [
        "data",
        "@context",
        "@type",
        "@id"
    ]
}

=== PlatformOfTrust/standards/v2/DataExample/Identity/Event.json
{
    "@context": "https://standards-ontotest.oftrust.net/v2/Context/Identity/Event/",
    "@type": "Event",
    "@id": "",
    "data": {
        "endDateTime": "",
        "duration": "",
        "categorizationLocal": "",
        "name": "",
        "startDateTime": "",
        "descriptionGeneral": "",
        "url": ""
    },
    "metadata": {
        "updatedBy": "",
        "createdAt": "",
        "updatedAt": "",
        "createdBy": ""
    },
    "locationName": ""
}
