=== PlatformOfTrust/standards/v2/Schema/Identity/Element/BuildingElement/Storey.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "properties": {
        "@context": {
            "type": "string",
            "minLength": 1,
            "const": "https://standards-ontotest.oftrust.net/v2/Context/Identity/Element/BuildingElement/Storey/"
        },
        "@type": {
            "type": "string",
            "minLength": 1,
            "enum": [
                "Storey"
            ],
            "const": "Storey"
        },
        "data": {
            "title": "",
            "description": "",
            "type": "object",
            "properties": {
                "areaNet": {
                    "title": "Net area",
                    "description": "Net area size",
                    "type": "string"
                },
                "colorCode": {
                    "title": "Color code",
                    "description": "Color code",
                    "type": "string"
                },
                "url": {
                    "title": "URL address",
                    "description": "URL address",
                    "type": "string"
                },
                "height": {
                    "title": "Height",
                    "description": "Height",
                    "type": "string"
                },
                "width": {
                    "title": "Width",
                    "description": "Object width",
                    "type": "string"
                },
                "additionalInformation": {
                    "title": "Additional information",
                    "description": "Additional information",
                    "type": "string",
                    "examples": [
                        "Our laminated logs are glued from two or more planed blanks in a way that the heartwood will stay on the logs surface. This is done to ensure that cracking and bending stay minimal."
                    ]
                },
                "length": {
                    "title": "Length",
                    "description": "Lenght",
                    "type": "string"
                },
                "descriptionGeneral": {
                    "title": "Description",
                    "description": "Description",
                    "type": "string"
                },
                "volume": {
                    "title": "Volume",
                    "description": "Volume of the object",
                    "type": "string"
                },
                "sizeAreaLivingAudited": {
                    "title": "Audited living area size",
                    "description": "Size of audited area suitable for, or used for, living",
                    "type": "string"
                },
                "status": {
                    "title": "Life-cycle status",
                    "description": "Life-cycle status",
                    "type": "string"
                },
                "name": {
                    "title": "Name",
                    "description": "Name",
                    "type": "string"
                },
                "colorName": {
                    "title": "Color",
                    "description": "Color name",
                    "type": "string"
                },
                "ifcElementName": {
                    "title": "IFC element name",
                    "description": "Element name based on IFC standard",
                    "type": "string"
                },
                "thickness": {
                    "title": "Thickness",
                    "description": "Thickness",
                    "type": "string"
                },
                "ifcGuid": {
                    "title": "IFC GUID",
                    "description": "IFC standard based Globally Unique Identifier",
                    "type": "string"
                },
                "weight": {
                    "title": "Weight",
                    "description": "Object weight",
                    "type": "string"
                },
                "areaGross": {
                    "title": "Gross area",
                    "description": "Gross area size",
                    "type": "string"
                },
                "ifcElementType": {
                    "title": "IFC element type",
                    "description": "Element type based on IFC standard",
                    "type": "string"
                },
                "categorizationLocal": {
                    "title": "Local category",
                    "description": "Categorisation name given locally",
                    "type": "string"
                },
                "idLocal": {
                    "title": "Local identifier",
                    "description": "Locally given identifier",
                    "type": "string"
                }
            }
        },
        "metadata": {
            "title": "Metadata",
            "description": "Metadata container",
            "type": "object",
            "properties": {
                "createdAt": {
                    "title": "Creation time",
                    "description": "Time when the data is created",
                    "type": "string"
                },
                "updatedAt": {
                    "title": "Update time",
                    "description": "Time when the data is updated",
                    "type": "string"
                },
                "updatedBy": {
                    "title": "Updater",
                    "description": "Updater of an identity",
                    "type": "string"
                },
                "createdBy": {
                    "title": "Creator",
                    "description": "Creator of and identity",
                    "type": "string"
                }
            }
        },
        "@id": {
            "title": "",
            "description": "",
            "type": "string"
        }
    },
    "required": [
        "data",
        "@context",
        "@type",
        "@id"
    ]
}

=== PlatformOfTrust/standards/v2/DataExample/Identity/Element/BuildingElement/Storey.json
{
    "@context": "https://standards-ontotest.oftrust.net/v2/Context/Identity/Element/BuildingElement/Storey/",
    "@type": "Storey",
    "@id": "",
    "data": {
        "thickness": "",
        "volume": "",
        "idLocal": "",
        "weight": "",
        "areaNet": "",
        "categorizationLocal": "",
        "name": "",
        "url": "",
        "ifcGuid": "",
        "width": "",
        "length": "",
        "height": "",
        "ifcElementType": "",
        "status": "",
        "additionalInformation": "Our laminated logs are glued from two or more planed blanks in a way that the heartwood will stay on the logs surface. This is done to ensure that cracking and bending stay minimal.",
        "areaGross": "",
        "descriptionGeneral": "",
        "ifcElementName": "",
        "colorName": "",
        "colorCode": "",
        "sizeAreaLivingAudited": ""
    },
    "metadata": {
        "updatedBy": "",
        "createdBy": "",
        "createdAt": "",
        "updatedAt": ""
    }
}
